name: ci

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Validate branch
      if: github.ref != 'refs/heads/main'
      runs: |
        echo 'Invalid branch!!'
        exit 1

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
